# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          shl13 Blog
paginate:       5
baseurl:        ''
url:            "https://shl13.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         shl13
  email:        selim@student.42seoul.kr

# Gems -> plugins
plugins:
  - jekyll-paginate 
  - jekyll-seo-tag
  - jekyll-feed
